name: CI/CD

on:
  push:
    branches:
      - homework_15

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-web-server .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-web-server:latest

#    - name: Deploy to server
#      run: |
#        docker stop my-web-server || true
#        docker rm my-web-server || true
#        docker run -d --name my-web-server -p 80:5000 my-web-server:latest